// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN6PYhpOljB_0nRBxMbkkknmUVSin5BmM',
    appId: '1:748787298900:web:23c052836c0dfd13d533c1',
    messagingSenderId: '748787298900',
    projectId: 'nihongo-499c1',
    authDomain: 'nihongo-499c1.firebaseapp.com',
    storageBucket: 'nihongo-499c1.firebasestorage.app',
    measurementId: 'G-6J4ZET8704',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ1sy2m3uZzgyXYwbOKSNKnxWNHSGLIPM',
    appId: '1:748787298900:android:2694ca43380397aed533c1',
    messagingSenderId: '748787298900',
    projectId: 'nihongo-499c1',
    storageBucket: 'nihongo-499c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Kb3fIqxBVNYZHwWIRd3EKznmLSWQNSs',
    appId: '1:748787298900:ios:0b19fd6982e223ded533c1',
    messagingSenderId: '748787298900',
    projectId: 'nihongo-499c1',
    storageBucket: 'nihongo-499c1.firebasestorage.app',
    iosBundleId: 'com.example.flashcardQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Kb3fIqxBVNYZHwWIRd3EKznmLSWQNSs',
    appId: '1:748787298900:ios:0b19fd6982e223ded533c1',
    messagingSenderId: '748787298900',
    projectId: 'nihongo-499c1',
    storageBucket: 'nihongo-499c1.firebasestorage.app',
    iosBundleId: 'com.example.flashcardQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN6PYhpOljB_0nRBxMbkkknmUVSin5BmM',
    appId: '1:748787298900:web:c5338f59954b472ed533c1',
    messagingSenderId: '748787298900',
    projectId: 'nihongo-499c1',
    authDomain: 'nihongo-499c1.firebaseapp.com',
    storageBucket: 'nihongo-499c1.firebasestorage.app',
    measurementId: 'G-6ZERNXEXZV',
  );
}
